### ISSUE TITLE
SNI remote target causes [SSL: WRONG_VERSION_NUMBER] wrong version number

### ISSUE THREAD

**Issue by rbeede** [gkbrk/slowloris#48] opened 2020-12-02 20:44 UTC
When running with a command line like:
`python3 slowloris.py -s 100 -v -ua -p 443 --https example.com`

If the remote target has strict requirements for SNI hostname checks then the connection can fail with:

> [SSL: WRONG_VERSION_NUMBER] wrong version number

The fix was to use Python3 library methods to change
`s = ssl.wrap_socket(s)`

to

`    context = ssl.create_default_context()`
`    s = context.wrap_socket(s,server_hostname=ip)`

**Comment by gkbrk** [comment] 2020-12-03 08:08
Thanks for the report, it is indeed problematic to not send SNI information when wrapping the socket with TLS.

**Comment by richstokes** [comment] 2021-03-23 18:59
I tried this fix, but still getting `[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)`

**Comment by gkbrk** [comment] 2021-04-02 21:03
HI @rbeede, this issue should be fixed now. Please let me know if there are still problems.

@richstokes your problem might be caused by not setting the HTTPS port. Can you try with `--https --port 443` and report back if there are still problems?

**Comment by gkbrk** [comment] 2021-05-08 16:37
As I haven't received an update, I'm assuming this issue is fixed.

**Closed by gkbrk** 2021-05-08 16:37 UTC
Labels: bug, enhancement, good first issue
